################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../pjlib/src/pj/activesock.c \
../pjlib/src/pj/addr_resolv_linux_kernel.c \
../pjlib/src/pj/addr_resolv_sock.c \
../pjlib/src/pj/array.c \
../pjlib/src/pj/config.c \
../pjlib/src/pj/ctype.c \
../pjlib/src/pj/errno.c \
../pjlib/src/pj/except.c \
../pjlib/src/pj/extra-exports.c \
../pjlib/src/pj/fifobuf.c \
../pjlib/src/pj/file_access_unistd.c \
../pjlib/src/pj/file_access_win32.c \
../pjlib/src/pj/file_io_ansi.c \
../pjlib/src/pj/file_io_win32.c \
../pjlib/src/pj/guid.c \
../pjlib/src/pj/guid_simple.c \
../pjlib/src/pj/guid_uuid.c \
../pjlib/src/pj/guid_win32.c \
../pjlib/src/pj/hash.c \
../pjlib/src/pj/ioqueue_common_abs.c \
../pjlib/src/pj/ioqueue_dummy.c \
../pjlib/src/pj/ioqueue_epoll.c \
../pjlib/src/pj/ioqueue_linux_kernel.c \
../pjlib/src/pj/ioqueue_select.c \
../pjlib/src/pj/ioqueue_winnt.c \
../pjlib/src/pj/ip_helper_generic.c \
../pjlib/src/pj/ip_helper_win32.c \
../pjlib/src/pj/list.c \
../pjlib/src/pj/lock.c \
../pjlib/src/pj/log.c \
../pjlib/src/pj/log_writer_printk.c \
../pjlib/src/pj/log_writer_stdout.c \
../pjlib/src/pj/os_core_linux_kernel.c \
../pjlib/src/pj/os_core_unix.c \
../pjlib/src/pj/os_core_win32.c \
../pjlib/src/pj/os_error_linux_kernel.c \
../pjlib/src/pj/os_error_unix.c \
../pjlib/src/pj/os_error_win32.c \
../pjlib/src/pj/os_info.c \
../pjlib/src/pj/os_rwmutex.c \
../pjlib/src/pj/os_time_bsd.c \
../pjlib/src/pj/os_time_common.c \
../pjlib/src/pj/os_time_linux_kernel.c \
../pjlib/src/pj/os_time_unix.c \
../pjlib/src/pj/os_time_win32.c \
../pjlib/src/pj/os_timestamp_common.c \
../pjlib/src/pj/os_timestamp_linux_kernel.c \
../pjlib/src/pj/os_timestamp_posix.c \
../pjlib/src/pj/os_timestamp_win32.c \
../pjlib/src/pj/pool.c \
../pjlib/src/pj/pool_buf.c \
../pjlib/src/pj/pool_caching.c \
../pjlib/src/pj/pool_dbg.c \
../pjlib/src/pj/pool_policy_kmalloc.c \
../pjlib/src/pj/pool_policy_malloc.c \
../pjlib/src/pj/rand.c \
../pjlib/src/pj/rbtree.c \
../pjlib/src/pj/sock_bsd.c \
../pjlib/src/pj/sock_common.c \
../pjlib/src/pj/sock_linux_kernel.c \
../pjlib/src/pj/sock_qos_bsd.c \
../pjlib/src/pj/sock_qos_common.c \
../pjlib/src/pj/sock_qos_dummy.c \
../pjlib/src/pj/sock_qos_wm.c \
../pjlib/src/pj/sock_select.c \
../pjlib/src/pj/ssl_sock_common.c \
../pjlib/src/pj/ssl_sock_dump.c \
../pjlib/src/pj/ssl_sock_ossl.c \
../pjlib/src/pj/string.c \
../pjlib/src/pj/symbols.c \
../pjlib/src/pj/timer.c \
../pjlib/src/pj/types.c \
../pjlib/src/pj/unicode_win32.c 

OBJS += \
./pjlib/src/pj/activesock.o \
./pjlib/src/pj/addr_resolv_linux_kernel.o \
./pjlib/src/pj/addr_resolv_sock.o \
./pjlib/src/pj/array.o \
./pjlib/src/pj/config.o \
./pjlib/src/pj/ctype.o \
./pjlib/src/pj/errno.o \
./pjlib/src/pj/except.o \
./pjlib/src/pj/extra-exports.o \
./pjlib/src/pj/fifobuf.o \
./pjlib/src/pj/file_access_unistd.o \
./pjlib/src/pj/file_access_win32.o \
./pjlib/src/pj/file_io_ansi.o \
./pjlib/src/pj/file_io_win32.o \
./pjlib/src/pj/guid.o \
./pjlib/src/pj/guid_simple.o \
./pjlib/src/pj/guid_uuid.o \
./pjlib/src/pj/guid_win32.o \
./pjlib/src/pj/hash.o \
./pjlib/src/pj/ioqueue_common_abs.o \
./pjlib/src/pj/ioqueue_dummy.o \
./pjlib/src/pj/ioqueue_epoll.o \
./pjlib/src/pj/ioqueue_linux_kernel.o \
./pjlib/src/pj/ioqueue_select.o \
./pjlib/src/pj/ioqueue_winnt.o \
./pjlib/src/pj/ip_helper_generic.o \
./pjlib/src/pj/ip_helper_win32.o \
./pjlib/src/pj/list.o \
./pjlib/src/pj/lock.o \
./pjlib/src/pj/log.o \
./pjlib/src/pj/log_writer_printk.o \
./pjlib/src/pj/log_writer_stdout.o \
./pjlib/src/pj/os_core_linux_kernel.o \
./pjlib/src/pj/os_core_unix.o \
./pjlib/src/pj/os_core_win32.o \
./pjlib/src/pj/os_error_linux_kernel.o \
./pjlib/src/pj/os_error_unix.o \
./pjlib/src/pj/os_error_win32.o \
./pjlib/src/pj/os_info.o \
./pjlib/src/pj/os_rwmutex.o \
./pjlib/src/pj/os_time_bsd.o \
./pjlib/src/pj/os_time_common.o \
./pjlib/src/pj/os_time_linux_kernel.o \
./pjlib/src/pj/os_time_unix.o \
./pjlib/src/pj/os_time_win32.o \
./pjlib/src/pj/os_timestamp_common.o \
./pjlib/src/pj/os_timestamp_linux_kernel.o \
./pjlib/src/pj/os_timestamp_posix.o \
./pjlib/src/pj/os_timestamp_win32.o \
./pjlib/src/pj/pool.o \
./pjlib/src/pj/pool_buf.o \
./pjlib/src/pj/pool_caching.o \
./pjlib/src/pj/pool_dbg.o \
./pjlib/src/pj/pool_policy_kmalloc.o \
./pjlib/src/pj/pool_policy_malloc.o \
./pjlib/src/pj/rand.o \
./pjlib/src/pj/rbtree.o \
./pjlib/src/pj/sock_bsd.o \
./pjlib/src/pj/sock_common.o \
./pjlib/src/pj/sock_linux_kernel.o \
./pjlib/src/pj/sock_qos_bsd.o \
./pjlib/src/pj/sock_qos_common.o \
./pjlib/src/pj/sock_qos_dummy.o \
./pjlib/src/pj/sock_qos_wm.o \
./pjlib/src/pj/sock_select.o \
./pjlib/src/pj/ssl_sock_common.o \
./pjlib/src/pj/ssl_sock_dump.o \
./pjlib/src/pj/ssl_sock_ossl.o \
./pjlib/src/pj/string.o \
./pjlib/src/pj/symbols.o \
./pjlib/src/pj/timer.o \
./pjlib/src/pj/types.o \
./pjlib/src/pj/unicode_win32.o 

C_DEPS += \
./pjlib/src/pj/activesock.d \
./pjlib/src/pj/addr_resolv_linux_kernel.d \
./pjlib/src/pj/addr_resolv_sock.d \
./pjlib/src/pj/array.d \
./pjlib/src/pj/config.d \
./pjlib/src/pj/ctype.d \
./pjlib/src/pj/errno.d \
./pjlib/src/pj/except.d \
./pjlib/src/pj/extra-exports.d \
./pjlib/src/pj/fifobuf.d \
./pjlib/src/pj/file_access_unistd.d \
./pjlib/src/pj/file_access_win32.d \
./pjlib/src/pj/file_io_ansi.d \
./pjlib/src/pj/file_io_win32.d \
./pjlib/src/pj/guid.d \
./pjlib/src/pj/guid_simple.d \
./pjlib/src/pj/guid_uuid.d \
./pjlib/src/pj/guid_win32.d \
./pjlib/src/pj/hash.d \
./pjlib/src/pj/ioqueue_common_abs.d \
./pjlib/src/pj/ioqueue_dummy.d \
./pjlib/src/pj/ioqueue_epoll.d \
./pjlib/src/pj/ioqueue_linux_kernel.d \
./pjlib/src/pj/ioqueue_select.d \
./pjlib/src/pj/ioqueue_winnt.d \
./pjlib/src/pj/ip_helper_generic.d \
./pjlib/src/pj/ip_helper_win32.d \
./pjlib/src/pj/list.d \
./pjlib/src/pj/lock.d \
./pjlib/src/pj/log.d \
./pjlib/src/pj/log_writer_printk.d \
./pjlib/src/pj/log_writer_stdout.d \
./pjlib/src/pj/os_core_linux_kernel.d \
./pjlib/src/pj/os_core_unix.d \
./pjlib/src/pj/os_core_win32.d \
./pjlib/src/pj/os_error_linux_kernel.d \
./pjlib/src/pj/os_error_unix.d \
./pjlib/src/pj/os_error_win32.d \
./pjlib/src/pj/os_info.d \
./pjlib/src/pj/os_rwmutex.d \
./pjlib/src/pj/os_time_bsd.d \
./pjlib/src/pj/os_time_common.d \
./pjlib/src/pj/os_time_linux_kernel.d \
./pjlib/src/pj/os_time_unix.d \
./pjlib/src/pj/os_time_win32.d \
./pjlib/src/pj/os_timestamp_common.d \
./pjlib/src/pj/os_timestamp_linux_kernel.d \
./pjlib/src/pj/os_timestamp_posix.d \
./pjlib/src/pj/os_timestamp_win32.d \
./pjlib/src/pj/pool.d \
./pjlib/src/pj/pool_buf.d \
./pjlib/src/pj/pool_caching.d \
./pjlib/src/pj/pool_dbg.d \
./pjlib/src/pj/pool_policy_kmalloc.d \
./pjlib/src/pj/pool_policy_malloc.d \
./pjlib/src/pj/rand.d \
./pjlib/src/pj/rbtree.d \
./pjlib/src/pj/sock_bsd.d \
./pjlib/src/pj/sock_common.d \
./pjlib/src/pj/sock_linux_kernel.d \
./pjlib/src/pj/sock_qos_bsd.d \
./pjlib/src/pj/sock_qos_common.d \
./pjlib/src/pj/sock_qos_dummy.d \
./pjlib/src/pj/sock_qos_wm.d \
./pjlib/src/pj/sock_select.d \
./pjlib/src/pj/ssl_sock_common.d \
./pjlib/src/pj/ssl_sock_dump.d \
./pjlib/src/pj/ssl_sock_ossl.d \
./pjlib/src/pj/string.d \
./pjlib/src/pj/symbols.d \
./pjlib/src/pj/timer.d \
./pjlib/src/pj/types.d \
./pjlib/src/pj/unicode_win32.d 


# Each subdirectory must supply rules for building sources it contributes
pjlib/src/pj/%.o: ../pjlib/src/pj/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


